IF OBJECT_ID('Items') IS NOT NULL
	DROP TABLE Items

IF OBJECT_ID('Users') IS NOT NULL
	DROP TABLE Users

CREATE TABLE Users (
	id INT IDENTITY PRIMARY KEY,
	[name] VARCHAR(300) NOT NULL,
	email VARCHAR(30) UNIQUE,
	[password] VARCHAR(100) NOT NULL
)
GO

CREATE TABLE Items (
	id INT IDENTITY PRIMARY KEY,
	[user_id] INT,
	arrival DATETIME NOT NULL DEFAULT GETDATE(),
	[address] VARCHAR(100) NOT NULL,
	phone VARCHAR(20) NOT NULL ,
	[description] VARCHAR(1000) NOT NULL,
	title VARCHAR(30) NOT NULL,
	price VARCHAR(20) NOT NULL,
	img VARCHAR(max) DEFAULT NULL,
	img1 VARCHAR(max) DEFAULT NULL,
	img2 VARCHAR(max)DEFAULT NULL,
	img3 VARCHAR(max)DEFAULT NULL,
	img4 VARCHAR(max)DEFAULT NULL,
	img5 VARCHAR(max) DEFAULT NULL
	CONSTRAINT FK_items_user_id FOREIGN KEY ([user_id]) REFERENCES Users(id)
)
GO
